# -*- coding: utf-8 -*-
"""casasnovas_Lab8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w2rwzi66NlWHsuIzudOXzO43p7O8xhsl
"""

import random
animated = {"The Old Man and the Sea" : 20,
            "Humdrum" : 7,
            "My Grandmother Ironed the King's Shirts" : 11,
            "3 Misses" : 11,
            "When the Day Breaks" : 10}

foreign = {"All about My Mother" : 101,
           "Himalaya: Caravan" : 108,
           "East-West" : 121,
           "Solomon and Gaenor" : 105,
           "Under the Sun" : 130}

all_movies = {}

all_movies.update(animated)
all_movies.update(foreign)

all_movies["Local Community Announcements"] = 12

#print(all_movies)

movie_names = []

for key, values in all_movies.items():
  if values > 10:
    movie_names.append(key)

#print(movie_names)

import random

movies_to_play = random.sample(movie_names, 5)

print()

print(" Movie name (length)  |  Total running time")
print("****************")
total_time = 0


for movie in movies_to_play:


    movie_lenght = all_movies[movie]
    total_time +=movie_lenght


    print( f"{movie} ({movie_lenght}) | {total_time}")